# Generated by Django 4.0.2 on 2022-07-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
