# Generated by Django 4.0.2 on 2022-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0002_remove_timelineitem_character_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, choices=[('Y', 'Years Old'), ('M', 'Months Old'), ('D', 'Days Old')], default='Y'),
        ),
    ]
