# Generated by Django 4.0.2 on 2022-07-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0003_alter_project_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelineitem',
            old_name='column_id',
            new_name='columnId',
        ),
    ]
