# Generated by Django 4.0.2 on 2022-06-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0003_alter_character_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
