# Generated by Django 4.0.2 on 2022-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0004_rename_column_id_timelineitem_columnid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
