# Generated by Django 4.0.2 on 2022-07-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0006_timelineitem_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineitem',
            name='position',
        ),
    ]
