# Generated by Django 4.0.2 on 2022-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0010_alter_timelineitem_beginningorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineitem',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='timelineCharacter', to='writeoff.Character'),
        ),
    ]
