# Generated by Django 4.0.2 on 2022-08-03 02:59

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('writeoff', '0011_alter_timelineitem_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
